// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get Profile",
  description: "Get Adarsh Sudhindra's professional profile summary including name, role, positioning statement, and contact links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Adarsh Sudhindra",
      role: "Chief Innovation Officer | Technologist | Innovator | Entrepreneur | TEDx Speaker | Author | UIUC Computer Science | Kellogg School of Business",
      summary: "As Chief Innovation Officer at Excelsoft Technologies since February 2026, Adarsh brings extensive experience in product management, product development, and educational technology. His work emphasizes driving forward innovative solutions that align with organizational goals and foster impactful advancements in e-learning. He builds products that make high-stakes learning and assessment smarter, fairer, and more secure.",
      email: "adarsh.sudhindra@gmail.com",
      linkedin: "https://www.linkedin.com/in/adarshsudhindra/",
      website: "https://adarsh-sudhindra.lovable.app"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var experiences = [
  {
    company: "Excelsoft Technologies",
    title: "Chief Innovation Officer",
    duration: "Feb 2026 \u2013 Present",
    location: "India",
    current: true,
    outcomes: [
      "Leading innovation strategy and product vision for AI-powered assessment and learning platforms serving millions globally",
      "Driving forward innovative solutions that align with organizational goals and foster impactful advancements in e-learning",
      "Spearheaded integrity and security frameworks for high-stakes national examinations",
      "Built and scaled cross-functional teams across product, engineering, and design",
      "Drove partnerships with national bodies and global certification organizations",
      "Progressed from Product Strategist \u2192 Senior Product Strategist \u2192 VP Products & Innovation \u2192 Chief Innovation Officer"
    ]
  },
  {
    company: "Excelsoft Technologies",
    title: "Vice President \u2014 Products & Innovation",
    duration: "Oct 2014 \u2013 Jan 2026",
    location: "Greater Boston, US",
    outcomes: [
      "Led product strategy and innovation for AI-powered assessment and learning platforms",
      "Spearheaded integrity and security frameworks for high-stakes national examinations",
      "Built and scaled cross-functional teams across product, engineering, and design"
    ]
  },
  {
    company: "Adobe Systems",
    title: "Senior Software Development Engineer",
    duration: "Jun 2011 \u2013 Sep 2014",
    location: "India",
    outcomes: [
      "Worked on Adobe Flash Professional and Adobe Web Technology Group",
      "Contributed to core product development for enterprise creative tools",
      "Progressed from Software Development Engineer to Senior Software Development Engineer"
    ]
  },
  {
    company: "IBM Software Labs",
    title: "Software Development Intern",
    duration: "2008 \u2013 2011",
    location: "India",
    outcomes: [
      "Contributed to enterprise collaboration and middleware platforms",
      "Gained foundational experience in large-scale software development"
    ]
  }
];
var get_experience_default = defineTool2({
  name: "get_experience",
  title: "Get Work Experience",
  description: "Get Adarsh Sudhindra's full work experience timeline including roles, companies, durations, locations, and key outcomes. Optionally filter to only the current role.",
  inputSchema: {
    current_only: z.boolean().optional().describe("If true, only return the current role.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ current_only }) => {
    const filtered = current_only ? experiences.filter((e) => e.current) : experiences;
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { experiences: filtered }
    };
  }
});

// src/lib/mcp/tools/get-education.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var education = [
  {
    institution: "Northwestern University \u2014 Kellogg School of Management",
    degree: "Executive Scholar \u2014 Products & Innovation",
    year: "Apr 2025 \u2013 Jul 2026"
  },
  {
    institution: "University of Illinois Urbana-Champaign",
    degree: "Master's Degree, Computer Science",
    year: "2013 \u2013 2014"
  },
  {
    institution: "The National Institute of Engineering, Mysore",
    degree: "Bachelor's Degree, Computer Science",
    year: "2004 \u2013 2008"
  }
];
var certifications = [
  {
    title: "Digital Marketing and Social Media Analytics",
    organization: "MIT Sloan School of Management",
    issued: "Jul 2016"
  }
];
var get_education_default = defineTool3({
  name: "get_education",
  title: "Get Education & Certifications",
  description: "Get Adarsh Sudhindra's academic background and professional certifications including institutions, degrees, and years.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = { education, certifications };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var contact = {
  email: "adarsh.sudhindra@gmail.com",
  linkedin: "https://www.linkedin.com/in/adarshsudhindra/",
  website: "https://adarsh-sudhindra.lovable.app",
  reasons_to_reach_out: [
    "Speaking invitations (conferences, panels, keynotes, workshops)",
    "Collaboration (product partnerships, advisory, joint ventures)",
    "Media & interviews (podcasts, articles, press inquiries)",
    "General inquiries"
  ]
};
var get_contact_default = defineTool4({
  name: "get_contact",
  title: "Get Contact Info",
  description: "Get Adarsh Sudhindra's contact information (email, LinkedIn, website) and the types of inquiries he welcomes.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "adarsh-sudhindra-mcp",
  title: "Adarsh Sudhindra",
  version: "0.1.0",
  instructions: "Query Adarsh Sudhindra's professional profile. Use get_profile for a summary, get_experience for the full work timeline (or the current role only), get_education for academic background and certifications, and get_contact for email and LinkedIn.",
  tools: [get_profile_default, get_experience_default, get_education_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
